// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexFlushSyncType_Type int32

const (
	IndexFlushSyncType_INDEX_MMAP_SYNC  IndexFlushSyncType_Type = 0
	IndexFlushSyncType_INDEX_MMAP_ASYNC IndexFlushSyncType_Type = 1
)

// Enum value maps for IndexFlushSyncType_Type.
var (
	IndexFlushSyncType_Type_name = map[int32]string{
		0: "INDEX_MMAP_SYNC",
		1: "INDEX_MMAP_ASYNC",
	}
	IndexFlushSyncType_Type_value = map[string]int32{
		"INDEX_MMAP_SYNC":  0,
		"INDEX_MMAP_ASYNC": 1,
	}
)

func (x IndexFlushSyncType_Type) Enum() *IndexFlushSyncType_Type {
	p := new(IndexFlushSyncType_Type)
	*p = x
	return p
}

func (x IndexFlushSyncType_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexFlushSyncType_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_api_proto_enumTypes[0].Descriptor()
}

func (IndexFlushSyncType_Type) Type() protoreflect.EnumType {
	return &file_api_api_proto_enumTypes[0]
}

func (x IndexFlushSyncType_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexFlushSyncType_Type.Descriptor instead.
func (IndexFlushSyncType_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{7, 0}
}

// Record represents the record data in bytes to send to the log server to be appended.
type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// BatchRecords represents a batch of `Record` to send.
type BatchRecords struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Batch []*Record `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
}

func (x *BatchRecords) Reset() {
	*x = BatchRecords{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchRecords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRecords) ProtoMessage() {}

func (x *BatchRecords) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRecords.ProtoReflect.Descriptor instead.
func (*BatchRecords) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *BatchRecords) GetBatch() []*Record {
	if x != nil {
		return x.Batch
	}
	return nil
}

// AppendRecordResp represents the server response from appending a record.
// The `offset` indicates the offset at which the record was assigned in the log
// while the `nbrOfStoredBytes` indicates the number of bytes that were stored in the log.
type AppendRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset           uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	NbrOfStoredBytes int64  `protobuf:"varint,2,opt,name=nbrOfStoredBytes,proto3" json:"nbrOfStoredBytes,omitempty"`
}

func (x *AppendRecordResp) Reset() {
	*x = AppendRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRecordResp) ProtoMessage() {}

func (x *AppendRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRecordResp.ProtoReflect.Descriptor instead.
func (*AppendRecordResp) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *AppendRecordResp) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AppendRecordResp) GetNbrOfStoredBytes() int64 {
	if x != nil {
		return x.NbrOfStoredBytes
	}
	return 0
}

// StreamAppendRecordResp represents the server stream response from appending a record
// from a batch append operation when using the `client.Send` api.
type StreamAppendRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp     *AppendRecordResp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Index    int64             `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	ErrorMsg string            `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *StreamAppendRecordResp) Reset() {
	*x = StreamAppendRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamAppendRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAppendRecordResp) ProtoMessage() {}

func (x *StreamAppendRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAppendRecordResp.ProtoReflect.Descriptor instead.
func (*StreamAppendRecordResp) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *StreamAppendRecordResp) GetResp() *AppendRecordResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *StreamAppendRecordResp) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *StreamAppendRecordResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// BatchAppendResp represents the server response from appending a batch of records in the same rpc call.
type BatchAppendResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*BatchAppendResp_RespWithOrder `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *BatchAppendResp) Reset() {
	*x = BatchAppendResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchAppendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAppendResp) ProtoMessage() {}

func (x *BatchAppendResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAppendResp.ProtoReflect.Descriptor instead.
func (*BatchAppendResp) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *BatchAppendResp) GetResponse() []*BatchAppendResp_RespWithOrder {
	if x != nil {
		return x.Response
	}
	return nil
}

// Offset represents the integer offset with which we can read a record from the log server.
type Offset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Offset) Reset() {
	*x = Offset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Offset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offset) ProtoMessage() {}

func (x *Offset) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offset.ProtoReflect.Descriptor instead.
func (*Offset) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *Offset) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// ReadRecordResp represents the server response from reading a record.
// The `record` holds the actual record in bytes while the `nbrOfReadBytes` indicates
// the number of bytes that we were able to read.
type ReadRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record         []byte `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	NbrOfReadBytes int64  `protobuf:"varint,2,opt,name=nbrOfReadBytes,proto3" json:"nbrOfReadBytes,omitempty"`
}

func (x *ReadRecordResp) Reset() {
	*x = ReadRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRecordResp) ProtoMessage() {}

func (x *ReadRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRecordResp.ProtoReflect.Descriptor instead.
func (*ReadRecordResp) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{6}
}

func (x *ReadRecordResp) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *ReadRecordResp) GetNbrOfReadBytes() int64 {
	if x != nil {
		return x.NbrOfReadBytes
	}
	return 0
}

// IndexFlushSyncType specifies wheter flushing should be done synchronously or asynchronously regarding the index
// mmap linked to the active segment.
type IndexFlushSyncType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value IndexFlushSyncType_Type `protobuf:"varint,1,opt,name=value,proto3,enum=api.IndexFlushSyncType_Type" json:"value,omitempty"`
}

func (x *IndexFlushSyncType) Reset() {
	*x = IndexFlushSyncType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexFlushSyncType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexFlushSyncType) ProtoMessage() {}

func (x *IndexFlushSyncType) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexFlushSyncType.ProtoReflect.Descriptor instead.
func (*IndexFlushSyncType) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{7}
}

func (x *IndexFlushSyncType) GetValue() IndexFlushSyncType_Type {
	if x != nil {
		return x.Value
	}
	return IndexFlushSyncType_INDEX_MMAP_SYNC
}

// LogMetaData holds informations about the state of the log regarding the `segmentsSize` which is
// the actual number of segments, the `oldestOffset` and `lastOffset` which represents the first and the last
// registred offsets.
type LogMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SegmentsSize int64  `protobuf:"varint,1,opt,name=segmentsSize,proto3" json:"segmentsSize,omitempty"`
	OldestOffset uint64 `protobuf:"varint,2,opt,name=oldestOffset,proto3" json:"oldestOffset,omitempty"`
	LastOffset   uint64 `protobuf:"varint,3,opt,name=lastOffset,proto3" json:"lastOffset,omitempty"`
}

func (x *LogMetaData) Reset() {
	*x = LogMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMetaData) ProtoMessage() {}

func (x *LogMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMetaData.ProtoReflect.Descriptor instead.
func (*LogMetaData) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{8}
}

func (x *LogMetaData) GetSegmentsSize() int64 {
	if x != nil {
		return x.SegmentsSize
	}
	return 0
}

func (x *LogMetaData) GetOldestOffset() uint64 {
	if x != nil {
		return x.OldestOffset
	}
	return 0
}

func (x *LogMetaData) GetLastOffset() uint64 {
	if x != nil {
		return x.LastOffset
	}
	return 0
}

// CollectOffset represents the integer offset with which we can trigger the segments collection operation
// which will delete segements containing records older than the given collect offset.
type CollectOffset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CollectOffset) Reset() {
	*x = CollectOffset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectOffset) ProtoMessage() {}

func (x *CollectOffset) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectOffset.ProtoReflect.Descriptor instead.
func (*CollectOffset) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{9}
}

func (x *CollectOffset) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type BatchAppendResp_RespWithOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// resp is the server append response of a record.
	Resp *AppendRecordResp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	// index indicates the original index of the record in the batch from where
	// it was appended. This index can help the caller to identify the record that was
	// successfully appended from the batch since the batch append operation is asynchronous
	// which means it doesn't preserve the original order reflected in the returned offset.
	Index int64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *BatchAppendResp_RespWithOrder) Reset() {
	*x = BatchAppendResp_RespWithOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchAppendResp_RespWithOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAppendResp_RespWithOrder) ProtoMessage() {}

func (x *BatchAppendResp_RespWithOrder) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAppendResp_RespWithOrder.ProtoReflect.Descriptor instead.
func (*BatchAppendResp_RespWithOrder) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4, 0}
}

func (x *BatchAppendResp_RespWithOrder) GetResp() *AppendRecordResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *BatchAppendResp_RespWithOrder) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_api_api_proto protoreflect.FileDescriptor

var file_api_api_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1c, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x31, 0x0a, 0x0c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12,
	0x21, 0x0a, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x62, 0x61, 0x74,
	0x63, 0x68, 0x22, 0x56, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x2a,
	0x0a, 0x10, 0x6e, 0x62, 0x72, 0x4f, 0x66, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6e, 0x62, 0x72, 0x4f, 0x66, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x75, 0x0a, 0x16, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x22, 0xa3, 0x01, 0x0a, 0x0f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x70, 0x70, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x50, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x57, 0x69, 0x74,
	0x68, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x72, 0x65, 0x73,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x1e, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x50, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x62, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x61, 0x64, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6e, 0x62, 0x72, 0x4f, 0x66,
	0x52, 0x65, 0x61, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x7b, 0x0a, 0x12, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x32, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x53,
	0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x31, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x49,
	0x4e, 0x44, 0x45, 0x58, 0x5f, 0x4d, 0x4d, 0x41, 0x50, 0x5f, 0x53, 0x59, 0x4e, 0x43, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x5f, 0x4d, 0x4d, 0x41, 0x50, 0x5f, 0x41,
	0x53, 0x59, 0x4e, 0x43, 0x10, 0x01, 0x22, 0x75, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x74,
	0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x6c, 0x64,
	0x65, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x6f, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x6c, 0x61, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x25, 0x0a,
	0x0d, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x32, 0xa2, 0x03, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x4c, 0x6f, 0x67, 0x52,
	0x70, 0x63, 0x12, 0x2e, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x0b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x38, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x70, 0x70, 0x65, 0x6e,
	0x64, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x1a, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x11,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x70, 0x70, 0x65, 0x6e,
	0x64, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2a, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x0b, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x3a, 0x0a, 0x05, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x53, 0x79, 0x6e, 0x63, 0x54,
	0x79, 0x70, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x4d, 0x65,
	0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0f, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x79, 0x6f, 0x79, 0x75, 0x2f, 0x63, 0x6f,
	0x6d, 0x4c, 0x6f, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData = file_api_api_proto_rawDesc
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_api_proto_rawDescData)
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_api_proto_goTypes = []interface{}{
	(IndexFlushSyncType_Type)(0),          // 0: api.IndexFlushSyncType.Type
	(*Record)(nil),                        // 1: api.Record
	(*BatchRecords)(nil),                  // 2: api.BatchRecords
	(*AppendRecordResp)(nil),              // 3: api.AppendRecordResp
	(*StreamAppendRecordResp)(nil),        // 4: api.StreamAppendRecordResp
	(*BatchAppendResp)(nil),               // 5: api.BatchAppendResp
	(*Offset)(nil),                        // 6: api.Offset
	(*ReadRecordResp)(nil),                // 7: api.ReadRecordResp
	(*IndexFlushSyncType)(nil),            // 8: api.IndexFlushSyncType
	(*LogMetaData)(nil),                   // 9: api.LogMetaData
	(*CollectOffset)(nil),                 // 10: api.CollectOffset
	(*BatchAppendResp_RespWithOrder)(nil), // 11: api.BatchAppendResp.RespWithOrder
	(*emptypb.Empty)(nil),                 // 12: google.protobuf.Empty
}
var file_api_api_proto_depIdxs = []int32{
	1,  // 0: api.BatchRecords.batch:type_name -> api.Record
	3,  // 1: api.StreamAppendRecordResp.resp:type_name -> api.AppendRecordResp
	11, // 2: api.BatchAppendResp.response:type_name -> api.BatchAppendResp.RespWithOrder
	0,  // 3: api.IndexFlushSyncType.value:type_name -> api.IndexFlushSyncType.Type
	3,  // 4: api.BatchAppendResp.RespWithOrder.resp:type_name -> api.AppendRecordResp
	1,  // 5: api.ComLogRpc.Append:input_type -> api.Record
	2,  // 6: api.ComLogRpc.BatchAppend:input_type -> api.BatchRecords
	2,  // 7: api.ComLogRpc.StreamBatchAppend:input_type -> api.BatchRecords
	6,  // 8: api.ComLogRpc.Read:input_type -> api.Offset
	8,  // 9: api.ComLogRpc.Flush:input_type -> api.IndexFlushSyncType
	12, // 10: api.ComLogRpc.GetMetaData:input_type -> google.protobuf.Empty
	10, // 11: api.ComLogRpc.CollectSegments:input_type -> api.CollectOffset
	3,  // 12: api.ComLogRpc.Append:output_type -> api.AppendRecordResp
	5,  // 13: api.ComLogRpc.BatchAppend:output_type -> api.BatchAppendResp
	4,  // 14: api.ComLogRpc.StreamBatchAppend:output_type -> api.StreamAppendRecordResp
	7,  // 15: api.ComLogRpc.Read:output_type -> api.ReadRecordResp
	12, // 16: api.ComLogRpc.Flush:output_type -> google.protobuf.Empty
	9,  // 17: api.ComLogRpc.GetMetaData:output_type -> api.LogMetaData
	12, // 18: api.ComLogRpc.CollectSegments:output_type -> google.protobuf.Empty
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchRecords); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamAppendRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchAppendResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Offset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexFlushSyncType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectOffset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchAppendResp_RespWithOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		EnumInfos:         file_api_api_proto_enumTypes,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_rawDesc = nil
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
